### ISSUE TITLE
Panel does not unhide when NOT empty in 1.7.0

### ISSUE THREAD

**Issue by nemchik** [steelbrain/linter-ui-default#487]
I just upgraded from 1.6.x to 1.7.0 and prior to upgrading when I switched to a tab where the linter panel was not empty it would unhide. Now in 1.7.0 the panel does not unhide when it is not empty. If I disable the "hide panel when empty" option the panel stays visible at all times when switching between tabs. Normally I keep the "hide panel when empty" option enabled and after upgrading to 1.7.0 if I show the panel and then switch to another tab it will hide the panel regardless if the panel is empty or not.

edited a bit to clarify what I meant

**Comment by nemchik** [comment]
If I had to guess I would think the issue is this commit https://github.com/steelbrain/linter-ui-default/commit/ecc29a3eca37de7e24cbd75e125300d2503ed3fd

Here's a step by step of how to reproduce the issue (should have included this initially):

1. Open two tab where one has nothing to display in the linter panel and the other does
1. Switch to the tab with no linter issues, the panel hides
1. Switch to the tab with linter issues, the panel does not show
1. Show the linter panel manually
1. Switch back to the tab with no linter issues, the panel hides
1. Switch back to the tab with linter issues, the panel does not show (problem)

I see the commit I mentioned is trying not to re-show a panel if it were hidden by the user, but as you can see in my description I have manually shown the panel on purpose and can't get it to come back when switching tabs back and forth.

**Comment by caleb531** [comment]
@nemchik @steelbrain I discovered a similar issue when my linter upgraded from 1.6.x to 1.7.0. I also have "Hide panel when empty" enabled, which hides the panel when there are no errors anymore for my project. However, when there are errors again, the linter panel will **not** automatically show, requiring me to open it manually if I want to see what the errors are. It's been rather annoying.

**Comment by steelbrain** [comment]
Sorry for letting this slip by, am working on a fix

**Comment by steelbrain** [comment]
Fixed in v1.7.1

**Comment by nemchik** [comment]
I have updated from 1.7.0 to 1.7.1 and it seems this issue is not resolved.

**Comment by steelbrain** [comment]
Oh, okay. Have you tried like restarting the editor? If not, I can investigate again

**Comment by nemchik** [comment]
I found there was an "Show Panel" which was unchecked (hovering shows the default is false). I don't recall that option being there prior to 1.7.1 but I may have overlooked it. Either way after upgrading to 1.7.1 and turning the "Show Panel" option on it seems everything is working as it did on 1.6.x

Thanks!

**Comment by nemchik** [comment]
Just did some digging through my config history and found I have had
```
"linter-ui-default": {
    "showPanel": true
},
```
enabled since version 1.1.0 on Mar 15, 2017. I have never changed that option according to my config backups (done with [sync-settings](https://atom.io/packages/sync-settings)). So I must have just overlooked that options existence, but also I have never disabled it, it seemed like upgrading to 1.7.x today disabled it for me (not sure if it was 1.7.1 or 1.7.0 that did it).

**Comment by SpadeAceman** [comment]
@nemchik, I can confirm that it was 1.7.0 which changed showPanel to false (or otherwise deactivated it somehow), as I kept re-checking it and it kept getting un-checked. After I updated to 1.7.1, I had to manually re-enable it one more time.

@steelbrain, it's probably worth notifying your users that they'll likely need to manually re-enable the "Show Panel" setting when moving from 1.7.0 to 1.7.1.

**Comment by caleb531** [comment]
@SpadeAceman When I upgraded from 1.7.0 to 1.7.1 just now, the "Show Panel" setting was still enabled for me, and the hiding bug was indeed fixed. I can't explain why you or @nemchik needed to re-enable it, so it's probably best to assume any existing preference won't be preserved.

**Comment by EvHaus** [comment]
My panel also broke in 1.7.0 and 1.7.1. I have `showPanel` set to `true` but the panel is not appearing at all. I don't even get the little arrow to bring it up manually, it's as if it's totally broken.

Clearing Atom settings, re-installing the plugin or re-installing Atom doesn't seem to help.

EDIT: Whoa... now the "Linter" panel is appearing as a new dedicated tab in Atom. That's weird.

**Comment by steelbrain** [comment]
Fixed in v1.8.1
