### ISSUE TITLE
All decorations get moved down to the bottom line after Prettier Format

### ISSUE THREAD

**Issue by alexgonch** [steelbrain/linter-ui-default#642]
As the title explains, if there are any ESLint UI decorations within the file (underlines, gutter indicators), they all get moved to the bottom line after using Prettier's Format function and stay that way until I reopen the file again. Notably, after this happens, even clicking on the issues through the bottom panel brings the cursor to that last line in the file. I have been seeing this behaviour for the past couple months.

I would really appreciate any input on how to work around this. Disabling decorations solves the issue but I'd love to keep them.

![image](https://user-images.githubusercontent.com/28286842/114910066-b03ab180-9dda-11eb-9f19-69eb7e8abcb4.png)
![image](https://user-images.githubusercontent.com/28286842/114910087-b761bf80-9dda-11eb-816f-6c4a21afa48c.png)

**Comment by aminya** [comment]
Is there a repository that I can try this on?

**Comment by alexgonch** [comment]
> Is there a repository that I can try this on?

I haven't been able to reproduce this in a clean repo, there must be some sort of a bad configuration in the private repo I'm having this issue in. I wasn't able to figure it out yet. I will update this thread if I stumble upon a solution.

**Comment by aminya** [comment]
I was able to reproduce this in one of the repositories. It gets resolved if you open/close the file, but it seems like a bug somewhere. 

Maybe it is related to Linter-eslint and not linter-ui-default.
https://github.com/AtomLinter/linter-eslint/releases

**Comment by alexgonch** [comment]
@aminya Hey, thanks for looking into this, really glad to hear you were able to reproduce!
One last piece of info from me that may or may not be helpful: when I have "Show Decorations" on and use Prettier format, which pushes all decorations down, clicking on the "Line" in the bottom panel brings the cursor to the bottom of the file as well despite showing the correct line and position of the lint warning/error.

![image](https://user-images.githubusercontent.com/28286842/116185858-ae78c400-a6df-11eb-99f5-3486edfb70e1.png)

**Comment by aminya** [comment]
Have you tried Atom nightly? Recently there were some breaking changes in Atom which are fixed in the nightly.

**Comment by alexgonch** [comment]
@aminya I just tried it and the problem persists in my repository.

**Comment by aminya** [comment]
The issue is quite hard to fix because we don't know why it happens. I need to debug the code to see why it is happening.

Is the repo open source? If so please share the link, so I can have a reproducible environment.

**Comment by alexgonch** [comment]
@aminya Unfortunately, it's private, and I was not able to reproduce this issue in any of my open repos.
